[general]
os_name = "fry-os"
os_version = "23.3.2"

[openwrt]
repo = "https://git.openwrt.org/openwrt/openwrt.git"
tag = "v23.05.5"

[[openwrt.feeds]]
method = "src-git"
name = "fry_os_feed"
url = "https://github.com/Fry-Foundation/fry-os-feed.git"

[[openwrt.feeds]]
method = "src-git"
name = "openwisp_config"
url = "https://github.com/openwisp/openwisp-config.git"

[[openwrt.feeds]]
method = "src-git"
name = "openwisp_monitoring"
url = "https://github.com/openwisp/openwrt-openwisp-monitoring.git"
