[general]
codename = "Prometheus"
brand = "Fry"
model = "Prometheus"

[build]
target = "mediatek"
subtarget = "filogic"
device_profile = "comfast_cf-wa933"

[packages]
base = [
    "curl",
    "libcurl",
    "ca-certificates",
    "lua",
    "lua-cjson",
    "luafilesystem",
    "liblua",
    "libuci-lua",
    "libubus-lua",
    # Enterprise networks
    "wpad",
    "radsecproxy",
    # OpenWISP
    "openwisp-config",
    "openwisp-monitoring",
    "netjson-monitoring",
    "openvpn-openssl",
    # Captive portal
    "opennds",
    "php8",
    "php8-cli",
    "php8-mod-openssl",
    "dnsmasq-full",
    "dnsmasq_full_dhcp",
    "dnsmasq_full_ipset",
    "ipset",
    # Fry services
    "fry-os-api",
    "fry-os-services",
]
