[general]
codename = "Genesis"
brand = "Wayru"
model = "Genesis"

[build]
target = "ath79"
subtarget = "generic"
device_profile = "comfast_cf-e375ac"

[packages]
base = [
    "curl",
    "libcurl",
    "ca-certificates",
    "lua",
    "lua-cjson",
    "luafilesystem",
    "liblua",
    "libuci-lua",
    "libubus-lua",
    # Enterprise networks
    "wpad",
    # OpenWISP
    "openwisp-config",
    "openwisp-monitoring",
    "netjson-monitoring",
    "openvpn-openssl",
    # Captive portal
    "opennds",
    "php8",
    "php8-cli",
    "php8-mod-openssl",
    "dnsmasq-full",
    "dnsmasq_full_dhcp",
    "dnsmasq_full_ipset",
    "ipset",
    # Wayru services
    "wayru-os-api",
    "wayru-os-services",
]
